In [3]:
import numpy as np


# Part 1

In [12]:
def array_factory(mode:str="zeros",shape=(1,1),value:float=2):
    ''' 
        Creates various NumPy arrays based on the specified mode.

        Parameters
        ----------
        mode : str, default='zeros'
            The type of array to generate.
            Supported modes: 'zeros', 'ones', 'full', 'identity'.
        shape : int or tuple of int, default=(1, 1)
            The desired shape/dimensions of the array. For 'identity',
            it represents the matrix size (N x N).
        value : scalar, optional (default=None)
            The value to fill the array with when mode is 'full'.

        Returns
        -------
        np.ndarray
            The generated NumPy array matching the mode and shape.

        Raises
        ------
        ValueError
            If an unsupported mode is provided or if mode is 'full' and value is None.

        Examples
        --------
        >>> array_factory('zeros', (2, 3))
        >>> array_factory('full', (3, 2), value=3)
        >>> array_factory('identity', 4)    
        
        
    
    '''
    try:
        if mode=="zeros":
            mat= np.zeros(shape)
            return f"{mat}\n" 

        elif mode=="full" or mode=="ones" or mode=="identity":
            if mode=="ones":
                mat=np.full(shape,1)
            elif mode=="full" or "identity":
                mat= np.full(shape,value)
        
            return f"{mat}\n" 
    except TypeError:
        print("enter real values")
    except ValueError:
        print("enter a valid number for a matrix shape")

print(array_factory("zeros",(3,2),3))
print(array_factory("zeros",(0,0),3))
print(array_factory("identity",(2,2),3))
print(array_factory("ones",(3,4),3))
array_factory("full",(3,2),8)

print(array_factory("zeros",2,"ss"))
print(array_factory("zeros",-1,3))

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[]

[[3 3]
 [3 3]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

[0. 0.]

enter a valid number for a matrix shape
None


# part 2

In [44]:
from typing import Any, Sequence, Tuple, Union
import numpy as np


def secure_reshape_and_stack(
    data1: Sequence[Any],
    data2: Sequence[Any],
    new_shape: Union[int, Tuple[int, ...]],
) -> np.ndarray:
    """Validates and converts inputs to NumPy arrays, reshapes the first dataset,

    and vertically stacks both datasets into a single matrix.

    Parameters
    ----------
    data1 : Sequence[Any]
        The first flat or structured dataset to be reshaped.
    data2 : Sequence[Any]
        The second dataset to be stacked vertically with the reshaped data1.
    new_shape : Union[int, Tuple[int, ...]]
        The target shape (rows, columns) to reshape data1 into.

    Returns
    -------
    np.ndarray
        The vertically stacked matrix combining reshaped data1 and data2.

    Raises
    ------
    ValueError
        If data1 cannot be reshaped to new_shape, or if column dimensions
        mismatch during vertical stacking.
    """
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = np.reshape(arr1, new_shape)

        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")
    
list_1=[[17,30,0]
        ,[9,32,3]]

list_2=[6,9,7,8,2,15]
secure_reshape_and_stack(list_2,list_1,(2,3))

array([[ 6,  9,  7],
       [ 8,  2, 15],
       [17, 30,  0],
       [ 9, 32,  3]])