In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])
x.shape

(3,)

In [4]:
def convert_dtype(arr,dtype):
    try:
        arr= np.asarray(arr)
        return arr.astype(dtype)
    except TypeError as e :
        raise TypeError(f"Invalid Target data Type:{dtype}")from e
    except ValueError as e :
            raise ValueError(f"Invalid Target data Type:{dtype}")from e

In [15]:
lst=([1,2.3,3])
print(lst)
arr=convert_dtype(lst,int)
type(lst[0])

[1, 2.3, 3]


list

In [21]:
mat= np.zeros((3,4))
mat_2=np.full((3,3),2)
print(mat)
mat_2

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
def init_array(shape,value:(float)=0):
    return np.full(shape,value)

In [23]:
my_array=init_array((3,3),6)
my_array

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [24]:
def init_weights(n_feature,method="zero",seed=None):
    if not isinstance(n_feature,int):
   
        raise TypeError(f"{n_feature}must be int")
    if n_feature<=0:
        raise TypeError(f"{n_feature} must be >0")
    if method=="random":
        if seed is not None:
            np.random.seed(seed)
        return np.random.randn(n_feature)*0.03
    raise ValueError(f"un supported  method type ")


In [35]:
init_weights(2,"random")

array([ 0.01020424, -0.0138585 ])

In [36]:
s= ["ss","121","12sa"]
np.random.choice(s,(3,2))

array([['ss', 'ss'],
       ['ss', '12sa'],
       ['ss', '121']], dtype='<U4')


## شرح الكود

هذا الكود يقوم بحفظ مصفوفتين `NumPy` في ملف واحد باسم `file_da.npz` ثم قراءتهما مرة أخرى:



In [ ]:
import numpy as np

mat1 = np.ones((3, 4))
mat2 = np.zeros((3, 4))

np.savez('file_da.npz', ones_mat=mat1, zeros_mat=mat2)

with np.load('file_da.npz') as file:
    loaded1 = file['ones_mat']
    loaded2 = file['zeros_mat']



### ماذا يحدث؟
- `np.ones((3,4))` → إنشاء مصفوفة 3×4 مليئة بـ 1
- `np.zeros((3,4))` → إنشاء مصفوفة 3×4 مليئة بـ 0
- `np.savez(...)` → حفظ كلا المصفوفتين داخل ملف واحد
- `np.load(...)` → فتح الملف واسترجاع كل مصفوفة حسب اسمها:
  - `file['ones_mat']`
  - `file['zeros_mat']`

### النتيجة التي تم التحقق منها
تم تشغيل نفس المثال في البيئة الحالية، وكانت النتيجة:



In [ ]:
(3, 4) (3, 4)
float64 float64
[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]



يعني:
- كل مصفوفة بقيت بنفس الشكل `(3,4)`
- النوع float64 لأن `ones` و `zeros` في `NumPy` يكونان نوع `float64` افتراضيًا

> ملاحظة: `np.savez` يتيح حفظ أكثر من مصفوفة في ملف واحد، بينما `np.save` يخصص لملف واحد فقط.

إذا رغبت، أستطيع أيضًا شرح الفرق بين:
- `np.save`
- `np.savez`
- `np.load`
- `np.loadtxt`

In [38]:
v1=np.array([1,2,3,5,8])
v2=np.array([2,5,4,5,1])
print(np.allclose(v1,v2,atol=2))
np.isclose(v1,v2,atol=2)

False


array([ True, False,  True,  True, False])

In [39]:
import pandas as pd


In [45]:
s= pd.Series([1,2,3,5,2,62,3], index=["A","B","C","D","E","F","I"])
s

A     1
B     2
C     3
D     5
E     2
F    62
I     3
dtype: int64

In [41]:
type(s)

pandas.Series

In [49]:
data=[[1,111,"abs"],
      [2,222,"sss"],
      [3,333,"SDS"],
      [4,444,"sda1"]]
data_2={'age':['22','33','24'],
        'salary':['2223','5000','3000'],
        'experience':[2,3,5]}

df=pd.DataFrame(data,columns=['col1','col2','col3'])
df_2=pd.DataFrame(data_2)
print(df_2)
print(df)


  age salary  experience
0  22   2223           2
1  33   5000           3
2  24   3000           5
   col1  col2  col3
0     1   111   abs
1     2   222   sss
2     3   333   SDS
3     4   444  sda1


In [52]:
'''data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]'''
 
data = {'col1':[1,2,3,4],
        'col2':[444,555,666,444],
        'col3':['abc','def','ghi','xyz']}
df = pd.DataFrame(data)
df
df['col3'].dtype


<StringDtype(storage='python', na_value=nan)>