In [2]:
import numpy as np
print(np.__version__)

2.5.2


In [13]:
arr_1=np.array([1, 2, 3, 4, 5])
arr_2=np.array([[[1, 2, 3], [4, 5, 6]]])
arr_3=arr_1*3
arr_4=arr_1+arr_3
array=np.array('s')
print(arr_1)
print(arr_1.ndim)
print(arr_2)
print(arr_2.ndim)
print(arr_3)
print(arr_3.ndim)
print(arr_4)
print(arr_4.ndim)
print(array)
print(array.ndim)


print(arr_2.shape)
print("## (layers, rows, columns) ")
print(arr_2.size)

[1 2 3 4 5]
1
[[[1 2 3]
  [4 5 6]]]
3
[ 3  6  9 12 15]
1
[ 4  8 12 16 20]
1
s
0
(1, 2, 3)
## (layers, rows, columns) 
6


In [16]:
arr_5=np.array([[[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9]]])

arr_6=np.array([[[1, 2, 3],[4, 5, 6], [7, 8, 9]],
                [[10, 11, 12],[13, 14, 15], [16, 17, 18]],
                [[36, 37, 38], [39, 40, 41], [42, 43, 44]]])
print(arr_5.shape)
print(arr_6.shape)
print(arr_5[0, 1, 2])

(1, 3, 3)
(3, 3, 3)
6


In [25]:
arr_6=np.array([[['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']],
                [['j', 'k', 'l'], ['m', 'n', 'o'], ['p', 'q', 'r']],
                [['s', 't', 'u'], ['v', 'w', 'x'], ['y', 'z',';)']]])

my_name=arr_6[0,0,1]+arr_6[0,0,0]+arr_6[2,0,0]+arr_6[0,1,1]+arr_6[1,0,2]+"  "+arr_6[2,2,2]
print(my_name)

basel  ;)


# Slicing

In [ ]:
## array slicing arr_6[start:end:step]
## or arr_6[start:end] or arr_6[start:end, start:end, start:end]
arr_6=np.array([[['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']],
                [['j', 'k', 'l'], ['m', 'n', 'o'], ['p', 'q', 'r']],
                [['s', 't', 'u'], ['v', 'w', 'x'], ['y', 'z',';)']]])

print(f" {arr_6[0:,0,0]} \n")

print(f" {arr_6[::2]} \n")



 ['a' 'j' 's'] 

 [[['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]

 [['s' 't' 'u']
  ['v' 'w' 'x']
  ['y' 'z' ';)']]] 

 [[['s' 't' 'u']
  ['v' 'w' 'x']
  ['y' 'z' ';)']]

 [['j' 'k' 'l']
  ['m' 'n' 'o']
  ['p' 'q' 'r']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]] 

 [[['s' 't' 'u']
  ['v' 'w' 'x']
  ['y' 'z' ';)']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]] 



In [54]:
print(f" {arr_6[::-1]} \n ##")
print(f" {arr_6[::-2]} \n")

 [[['s' 't' 'u']
  ['v' 'w' 'x']
  ['y' 'z' ';)']]

 [['j' 'k' 'l']
  ['m' 'n' 'o']
  ['p' 'q' 'r']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]] 
 ##
 [[['s' 't' 'u']
  ['v' 'w' 'x']
  ['y' 'z' ';)']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]] 



In [50]:

print(f" {arr_6[0:,0,0:3]} \n")

print(f"\n {arr_6[0: , 0 , 0:3:2]} \n")

 [['a' 'b' 'c']
 ['j' 'k' 'l']
 ['s' 't' 'u']] 


 [['a' 'c']
 ['j' 'l']
 ['s' 'u']] 



## arthrimatic

In [56]:
##scalar 
arr_6=np.array([1, 2, 3, 4, 5])

print(arr_6**2)
print(arr_6+6)

[ 1  4  9 16 25]
[ 7  8  9 10 11]


In [107]:
## vector

radii=np.array([1.03, 2.1, 3.8, 4.3, 5.2])
print(np.sqrt(radii))
print(np.exp(radii))## e^1.03 , e^2.1 , e^3.8 , e^4.3 , e^5.2
print(np.log(radii))## ln(1.03) , ln(2.1) , ln(3.8) , ln(4.3) , ln(5.2)
print(np.round(radii))
print(np.floor(radii))
print(np.ceil(radii))
print(np.max(radii))
print(np.argmax(radii))## index of max value
print(np.min(radii))
print(np.argmin(radii))## index of min value

print(np.mean(radii))
print(np.median(radii))
print(np.std(radii))## standard deviation
print(np.var(radii))## variance
print(np.percentile(radii, 25))## 25th percentile
print(np.percentile(radii, 50))## 50th percentile
print(np.percentile(radii, 75))## 75th percentile   
print(np.percentile(radii, 90))## 90th percentile
print(np.pi * (radii**2))## area of circle

[1.01488916 1.44913767 1.94935887 2.07364414 2.28035085]
[  2.80106583   8.16616991  44.70118449  73.6997937  181.27224188]
[0.0295588  0.74193734 1.33500107 1.45861502 1.64865863]
[1. 2. 4. 4. 5.]
[1. 2. 3. 4. 5.]
[2. 3. 4. 5. 6.]
5.2
4
1.03
0
3.286
3.8
1.5134014668950206
2.2903840000000004
2.1
3.8
4.3
4.84
[ 3.33291565 13.8544236  45.36459792 58.08804816 84.94866535]


In [89]:
arr_1=np.array([1, 2, 3, 4, 5])
arr_2=np.array([6, 7, 8, 9, 10])
print(np.add(arr_1, arr_2))## element-wise addition
print(np.subtract(arr_1, arr_2))## element-wise subtraction
print(np.multiply(arr_1, arr_2))## element-wise multiplication
print(np.divide(arr_1, arr_2))## element-wise division ## display last 2 decimal places

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [73]:
np.random.seed(0)## to get the same random numbers every time
rand_arr=np.random.randint(1, 100, size=(5, 5))
print(rand_arr)

[[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]]


In [95]:
scores=np.array([18, 25, 38, 42, 50])
print(scores>30)


[False False  True  True  True]


## Broadcasting

In [98]:
arrat_1=np.array([[1, 2, 3, 4, 5]])
arrat_2=np.array([[6, 7, 8, 9, 10]])
print(f"Concatenated along rows:\n{np.concatenate((arrat_1, arrat_2), axis=0)}\n")
print(f"Concatenated along columns:\n{np.concatenate((arrat_1, arrat_2), axis=1)}")

Concatenated along rows:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Concatenated along columns:
[[ 1  2  3  4  5  6  7  8  9 10]]


In [105]:
print(f"Stacked along rows:\n{np.vstack((arrat_1, arrat_2))}\n")
print(f"Stacked along columns:\n{np.hstack((arrat_1, arrat_2))}\n")


print(arrat_1.shape)
print(arrat_2.shape)

Stacked along rows:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Stacked along columns:
[[ 1  2  3  4  5  6  7  8  9 10]]

(1, 5)
(1, 5)


In [106]:
array_1=np.array([[1, 2, 3]])
array_2=np.array([[7], [10], [13]])
print(array_1.shape)
print(array_2.shape)
print(array_1*array_2)## broadcasting ضربهم ضرب cross product

(1, 3)
(3, 1)
[[ 7 14 21]
 [10 20 30]
 [13 26 39]]


# aggeragate Func

In [113]:
arr_9=np.array([[[1, 2, 3],    [4, 5, 6]],
                [[7, 8, 9],    [10, 11, 12]],
                [[13, 14, 15], [16, 17, 18]]])
print(arr_9.shape)
print(f"Sum along axis 0:\n {np.sum(arr_9, axis=0)}")## sum along axis 0 means sum along the first dimension (layers), resulting in a 2D array where each element is the sum of the corresponding elements across all layers.
print(f"Sum along axis 1:\n {np.sum(arr_9, axis=1)}")## sum along axis 1 means sum along the second dimension (rows), resulting in a 2D array where each element is the sum of the corresponding elements across all rows.
print(f"Sum along axis 2:\n {np.sum(arr_9, axis=2)}")## sum along axis 2 means sum along the third dimension (columns), resulting in a 2D array where each element is the sum of the corresponding elements across all columns.


(3, 2, 3)
Sum along axis 0:
 [[21 24 27]
 [30 33 36]]
Sum along axis 1:
 [[ 5  7  9]
 [17 19 21]
 [29 31 33]]
Sum along axis 2:
 [[ 6 15]
 [24 33]
 [42 51]]


## filtering

In [124]:
ages=np.array([[[18, 21, 30],    [40, 55, 62]],
                [[17, 18, 19],    [15, 11, 12]],
                [[13, 14, 15], [16, 17, 18]]])
teenagers=ages[ages<20]
seniors=ages[  (ages>23) & (ages<100)]
adult=np.where((ages>=20) & (ages<60), ages, 0)
print(teenagers)
print(seniors)
print(adult)

[18 17 18 19 15 11 12 13 14 15 16 17 18]
[30 40 55 62]
[[[ 0 21 30]
  [40 55  0]]

 [[ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]]]


# Random

In [133]:
rng=np.random.default_rng()## to get the same random numbers every time
print(rng.random(5))## 5 random numbers between 0 and 1
print(rng.integers(low=1, high=100, size=(5, 5)))## 5x5 random integers between 1 and 100

[0.09707955 0.92655914 0.29664983 0.32568948 0.96522941]
[[87 83 54 74  8]
 [17 14 29  3 14]
 [91 94 11 47 51]
 [18 66 69 21 37]
 [93 78 26 52 64]]


In [136]:
print(np.random.uniform(0, 1, 5))## to get the same random numbers every time

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [150]:
arr_5=np.array([[1, 2, 3], [4, 5, 6]])
arr_6=np.array([[7, 8, 9], [10, 11, 12]])
rng=np.random.default_rng()
fruits=np.array(['apple', 'banana', 'cherry', 'date', 'blueberry']) 
fruit=rng.choice(fruits)## random choice of 3 fruits without replacement
print(fruit)

apple


In [155]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.seed(0)## to get the same random numbers every time
rand_arr=np.random.randint(1, 100, size=(5, 5))
print(rand_arr)

[[41 16 73 23 44]
 [83 76  8 35 50]
 [96 76 86 48 64]
 [32 91 21 38 40]
 [68  5 43 52 39]]


In [ ]:
np.full((3, 3), rng.random(low=0, high=1)) ## 3x3 array filled with same random number between 0 and 1

array([[0.20128216, 0.20128216, 0.20128216],
       [0.20128216, 0.20128216, 0.20128216],
       [0.20128216, 0.20128216, 0.20128216]])

In [206]:
rand_arr=np.random.randint(-50, 50, size=(5, 5))## 5x5 random integers between -50 and 50
print(rand_arr)

[[ 40 -14 -10 -31   6]
 [-42  28  -1   1 -23]
 [ 17  29 -48 -28 -45]
 [-45  32  43 -38  42]
 [-44  -6 -45 -34  19]]
